server/account/urls.py
"""account urls."""
from django.urls import path

from account.views import AccountView

app_name = 'account'
urlpatterns = [
    path('', AccountView.as_view(), name='index')
]

server/project/urls.py
"""project urls."""
from django.urls import path, re_path

from project.views import ProjectListView, ProjectDetailView

app_name = 'project'

urlpatterns = [
    path('', ProjectListView.as_view(), name='index'),
    re_path(r'(?P<uid>\w+)/', ProjectDetailView.as_view(), name='detail'),
]

server/server/urls.py
from django.conf import settings
from django.contrib import admin
from django.conf.urls import static

from django.urls import path, include

from . import views

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('account/', include('account.urls')),
    path('project/', include('project.urls')),
]


if settings.DEBUG:
    urlpatterns += static.static(settings.MEDIA_URL,
                                 document_root=settings.MEDIA_ROOT)
    urlpatterns += static.static(settings.STATIC_URL,
                                 document_root=settings.STATIC_ROOT)

server/account/models.py
"""account models."""
from django.contrib.auth.hashers import (
    check_password, make_password
)
from django.db import models

from extension.modelutils import RandomFixedCharField


class Account(models.Model):

    uid = RandomFixedCharField('编号', max_length=32, unique=True)

    username = models.CharField('用户名', max_length=32, unique=True)
    password = models.CharField('密码', max_length=80)

    create_time = models.DateTimeField('创建时间', auto_now_add=True)
    update_time = models.DateTimeField('修改时间', auto_now=True)

    def __str__(self):
        return self.username

    class Meta:
        """Meta."""
        verbose_name = '用户'
        verbose_name_plural = '用户'

    def set_password(self, raw_password):
        self.password = make_password(raw_password)

    def check_password(self, raw_password):
        def setter(raw_password):
            self.set_password(raw_password)
            self.save(update_fields=['password'])
        return check_password(raw_password, self.password, setter)

server/project/models.py
"""project models."""
from django.db import models

from extension.modelutils import RandomFixedCharField


class Project(models.Model):

    uid = RandomFixedCharField('编号', max_length=32, unique=True)

    name = models.CharField('项目名称', max_length=32, unique=True)

    creator = models.ForeignKey(
        'account.Account', verbose_name='创建人', related_name='projects',
        on_delete=models.CASCADE)

    create_time = models.DateTimeField('创建时间', auto_now_add=True)
    update_time = models.DateTimeField('修改时间', auto_now=True)

    def __str__(self):
        return self.name

    class Meta:
        """Meta."""
        verbose_name = '项目'
        verbose_name_plural = '项目'

server/account/views.py
"""account views."""
from django.views import generic


class AccountView(generic.TemplateView):

    view_name = 'account_index'
    template_name = 'account/index.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        return context

server/project/views.py
"""project views."""
from django.views import generic

from project.models import Project


class ProjectListView(generic.TemplateView):

    view_name = 'project_index'
    template_name = 'project/index.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        projects = Project.objects.all()

        context.update({'projects': projects})
        return context


class ProjectDetailView(generic.TemplateView):

    view_name = 'project_detail'
    template_name = 'project/detail.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        uid = kwargs['uid']
        project = Project.objects.filter(uid=uid).first()

        context.update({'project': project})
        return context

server/server/views.py
"""server views."""
from django.views import generic


class IndexView(generic.TemplateView):
    """Index view."""

    view_name = 'index'

    template_name = 'index.html'

server/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="zh-Hans">

<head>
    <meta charset="UTF-8">
    <title>easydocs</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <meta name="keywords" content="python,blog">
    <meta name="description" content="codingcat">
    <link rel="stylesheet" href="{% static 'res/layui/css/layui.css' %}">
    <link rel="stylesheet" href="{% static 'res/css/global.css' %}">
    {% block extrastyle %}{% endblock extrastyle %}
</head>

<body>
    <div class="fly-header" style="background:#49505F;">
        <div class="layui-container">
          <a class="fly-logo" href="/"> <img src="{% static 'res/images/logo2.png' %}" alt="layui"></a>
            {% block topnav %}
                {% include 'topnav.html' %}
            {% endblock topnav %}
            <ul class="layui-nav fly-nav-user">
            </ul>
        </div>
    </div>

    {% block topPanel %}{% endblock topPanel %}

    <div class="layui-container">
        <div class="layui-row layui-col-space15">
            {% block mainer %}
                {% block leftBlock %} {% endblock leftBlock %}
            {% endblock mainer %}
        </div>
    </div>

    <div class="footer">
        <p><a href="/">easydocs</a> 2018 &copy; <a href="#">easydocs</a></p>
    </div>

    <script src="{% static 'res/layui/layui.js' %}"></script>
    <script src="{% static 'js/jquery.min.js' %}"></script>
    <script>
    $(function(){
        function footerPosition(){
            $(".footer").removeClass("fixed-bottom");
            var contentHeight = document.body.scrollHeight,//网页正文全文高度
                winHeight = window.innerHeight;//可视窗口高度，不包括浏览器顶部工具栏
            if(!(contentHeight > winHeight)){
                //当网页正文高度小于可视窗口高度时，为footer添加类fixed-bottom
                $(".footer").addClass("fixed-bottom");
            }

        }
        footerPosition();
        $(window).resize(footerPosition);
    });
    </script>
    {% block extrascript %}{% endblock extrascript %}

</body>

</html>

server/templates/index.html
{% extends 'base.html' %}{% load static %}

{% block topPanel %}
<div class="fly-panel fly-column">
    <div class="layui-container">
        <ul class="layui-clear">
            <li class="layui-hide-xs layui-this"><a href="/">首页</a></li>
            <li><a href="#">其他</a></li>
        </ul>

    </div>
</div>
{% endblock topPanel %}

{% block leftBlock %}
    <div class="layui-col-md8">

      <div class="fly-panel" style="margin-bottom: 0;">

        <ul class="article-list">
          {% for article in articles %}
          <li>
            <a href="#" class="fly-avatar">
              <img src="{% static 'res/images/codingcat.jpg' %}" alt="#">
            </a>
            <h2>
              <a href="{% url 'info:article_detail' article.uid %}">{{ article.title }}</a>
            </h2>
            <div class="fly-list-info">
              <a link>
                <cite>codincat</cite>
              </a>
              <span><i class="iconfont icon-shijian"></i> {{ article.creation_time|date:'Y-m-d' }}</span>
              <span class="fly-list-nums">
                <i class="iconfont icon-liulanyanjing" title="star"></i> 0
              </span>
            </div>
            <div class="short-intro" style="margin-top:15px;">
              <a href="{% url 'info:article_detail' article.uid %}" target="_blank" >
                <img src="{{ article.image.url }}" alt="">
              </a>
              <p class="fly-case-descv2">{{ article.intro }}</p>
            </div>
          </li>
          {% endfor %}

        </ul>

      </div>
    </div>
{% endblock leftBlock %}

server/templates/project/detail.html
{% extends 'base.html' %}{% load static %}
{% block topPanel %}
<div class="fly-panel fly-column">
    <div class="layui-container">
    </div>
</div>
{% endblock topPanel %}


{% block leftBlock %}
<style>
    .project-head {
        max-width: 1020px;
        margin: auto;
        font-size: 16px;
        color: #fff;
        background: #2d8cf0;
        border-radius: 4px;
        -webkit-box-shadow: 0 2px 3px #eee;
        box-shadow: 0 2px 3px #eee;
    }
    .head-content {
        padding: 20px;
    }
    .project-head .tag {
        width: 69%;
        font-size: 13px;
        margin-top: 16px;
        padding-right: 10px;

        background: rgba(0,0,0,.3);
        border-radius: 20px;
        overflow: hidden;
        text-overflow: ellipsis;
        white-space: nowrap;
    }
    .project-head .tag span {
        padding: 5px 10px;
        background: rgba(0,0,0,.5);
        display: inline-block;
        border-top-left-radius: 20px;
        border-bottom-left-radius: 20px;
        margin-right: 10px;
        width: 100px;
        text-align: center;
    }
    .project-head .right-content {
        width: 21%;
        border-top-right-radius: 4px;
        border-bottom-right-radius: 4px;
        -webkit-box-shadow: 0 0 3px #000;
        box-shadow: 0 0 3px #000;
        text-align: center;
        background: #252d47;
        position: absolute;
        right: 0;
        top: 0;
        bottom: 0;
        display: -webkit-box;
        display: -ms-flexbox;
        display: flex;
        -webkit-box-pack: center;
        -ms-flex-pack: center;
        justify-content: center;
        -webkit-box-align: center;
        -ms-flex-align: center;
        align-items: center;
    }
    .right-content img {
        width: 60px;
        height: 60px;
        border-radius: 50%;
        border: 2px solid #fff;
    }
    .right-content .author {
        padding: 2px 10px;
        font-size: 14px;
        margin-top: 10px;
        max-width: 200px;
        background: rgba(0,0,0,.3);
        border-radius: 20px;
        overflow: hidden;
        text-overflow: ellipsis;
        white-space: nowrap;
    }
</style>
<div class="layui-col-md12">
    <div class="project-head">
        <div class="head-content">
            <div class="em-spots" style=""></div>{{ project.name }}<p class="tag"><span>Base URL</span>/mock/5ad9b84dce613a62d3322d2f/
                </p><p class="tag"><span>Project ID</span> 5ad9b84dce613a62d3322d2f
                </p>

            <div class="right-content">
                <img src="//img.souche.com/29482f8a082b5015ef71d763b046cd6d.jpg">
                <p class="author">{{ project.creator }}</p>
            </div>

            </div>
        </div>
    </div>

</div>
{% endblock leftBlock %}

server/templates/project/index.html
{% extends 'base.html' %}{% load static %}

{% block topPanel %}
<div class="fly-panel fly-column">
    <div class="layui-container">
    </div>
</div>
{% endblock topPanel %}

{% block leftBlock %}
    <div class="layui-col-md8">
        {% for project in projects %}
            <div class="cardCover">
                <div class="cardBox">
                    <div class="box">
                        <a href="#"><div class="boxImg"><img src="{% static 'image/default.jpg' %}"></div></a>
                        <a href="{{ project.uid }}/">
                            <div class="boxContent">
                                <p class="boxTitle" title="{{ project.name }}">{{ project.name }}</p>
                                <p class="boxDesc" title="{{ project.intro|truncatechars:32 }}">{{ project.intro|truncatechars:32 }}</p>
                                <div class="boxBottom">
                                    <div class="bottom-box clearfix">
                                        <div class="evaluation-box l">
                                            <div class="author-info"><span></span></div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </a>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
{% endblock leftBlock %}

server/templates/topnav.html
<ul class="layui-nav fly-nav layui-hide-xs">
    <li class="layui-nav-item">
        <a href="/"><i class="layui-icon layui-icon-app"></i>工作台</a>
    </li>
    <li class="layui-nav-item">
        <a href="{% url 'project:index' %}"><i class="layui-icon layui-icon-template-1"></i>项目</a>
    </li>
    <li class="layui-nav-item">
        <a href="#"><i class="layui-icon layui-icon-read"></i>文档</a>
    </li>
</ul>
<ul class="layui-nav fly-nav-user">
    <li class="layui-nav-item"> <a class="layui-icon layui-icon-username
" href="{% url 'account:index' %}"></a></li>
    <li class="layui-nav-item">无声</li>
</ul>